#!/bin/bash
#####################################
# Decription: The purpose script file to calculate a student grade
# Name: Kanykei Akmatova
# Kanykei Akmatova, #040968369, 22W_CST8102_450, user_manager, March 21, 2022. 
#####################################

# Reading user's marks
echo -n "Enter Assignment mark (0 to 40): " 
read assignment
echo -n "Enter Test 1 mark (0 to 15): "
read test1
echo -n "Enter Test 2 mark (1 to 15): "
read test2
echo -n "Enter Final Exam mark (1 to 30): "
read exam
# CalculatingfinalGrade grade by sum of assignment,test1,test2,$finalGrade exam
((grade=assignment+test1+test2+exam))

# Grade Table
# 90 - 100 A+
# 85 - 89  A
# 80 - 84  A-
# 77 - 79  B+
# 73 - 76  B
# 70 - 72  B-
# 67 - 69  C+
# 63 - 66  C
# 60 - 62  C-
# 57 - 59  D+
# 53 - 56  D
# 50 - 52  D-
# 0 - 49   F

# Converting the number grade to letter grade
if [[ $grade -ge 90 && $grade -le 100 ]]
then
 finalGrade="A+"
elif [[ $grade -ge 85 && $grade -le 89 ]]
then
 finalGrade="A"
elif [[ $grade -ge 80 && $grade -le 84 ]]
then
 finalGrade="A-"
elif [[ $grade -ge 77 && $grade -le 79 ]]
then
 finalGrade="B+"
elif [[ $grade -ge 73 && $grade -le 76 ]]
then
 finalGrade="B"
elif [[ $grade -ge 70 && $grade -le 72 ]]
then
 finalGrade="B-"
elif [[ $grade -ge 67 && $grade -le 69 ]]
then
 finalGrade="C+"
elif [[ $grade -ge 63 && $grade -le 66 ]]
then
 finalGrade="C"
elif [[ $grade -ge 60 && $grade -le 62 ]]
then
 finalGrade="C-"
elif [[ $grade -ge 57 && $grade -le 59 ]]
then
 finalGrade="D+"
elif [[ $grade -ge 53 && $grade -le 56 ]]
then
 finalGrade="D"
elif [[ $grade -ge 50 && $grade -le 52 ]]
then
 finalGrade="D-"
elif [[ $grade -ge 0 && $grade -le 49 ]]
then
 finalGrade="F"
fi

# Spacing
echo
echo
# Grade letter grade
echo "Your final grade is $finalGrade"
echo
